### ISSUE TITLE
feat/question: make it possible to use with repository_dispatch event

### ISSUE THREAD

**Issue by ruscon** [wagoid/commitlint-github-action#121]
I want to use this [project](https://github.com/SvanBoxel/organization-workflows#action-inputs)

I have set up a simple workflow:
```yaml
name: commitlint

on:
  repository_dispatch:
    types: [org-workflow-bot]

jobs:
  register:
    runs-on: ubuntu-latest

    steps:
      - uses: SvanBoxel/organization-workflow@main
        with:
          id: ${{ github.event.client_payload.id }}
          callback_url: ${{ github.event.client_payload.callback_url }}
          sha: ${{ github.event.client_payload.sha }}
          run_id: ${{ github.run_id }}
          name: ${{ github.workflow }}
          enforce: true
          documentation: ".github/workflows/commitlint.md"

  commitlint:
    needs: [register]
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ github.event.client_payload.token }}

      - name: Lints Pull Request commits
        uses: wagoid/commitlint-github-action@v2
```

But it crashes because your action takes the last commit of the wrong repository 
should use: `ref: ${{ github.event.client_payload.sha }}`

is it possible to pass the required parameters?
