### ISSUE TITLE
Docs are terrible

### ISSUE THREAD

**Issue by rizet** [wagoid/commitlint-github-action#156]
I don't understand anything from these docs. Figuring out the configuration file was guesswork. I don't know where to put these "fields", like `configFile`, into.

**Comment by wagoid** [comment]
Hey @rizet, each of those inputs from the `Inputs` section of the readme can be passed in the `with` parameter of the step. You can see more info about this field [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith).

For `configFile` for example, ou can pass do following:

```yaml
name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v3
        with:
          configFile: commitlint.config.yml

```

If you have other doubts, let me know. If you want to add a PR making the docs less terrible, I'll be happy to merge it.
