### ISSUE TITLE
Should `fixup!` commits be valid?

### ISSUE THREAD

**Issue by johnallen3d** [wagoid/commitlint-github-action#326]
I'm just diving into (and falling in love with) the world of conventional commits! I've implemented this action and was surprised when it didn't fail after a particular push. I'm in the habit of making small "fixup" commits after opening a PR to clean up anything noticed in the review. I expected those to cause `commitlint` to fail with the idea that I'd do an interactive rebase when ready for re-review/merge. However, I noticed that the `commitlint` action passed when I pushed a `fixup` commit.

![image](https://user-images.githubusercontent.com/184915/151251979-46552bba-0fa6-4022-b83f-1160aab4ce3a.png)

Here's my action configuration:

```yaml
name: Lint Commit Messages

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
```
