### ISSUE TITLE
Not pulling in specified config file

### ISSUE THREAD

**Issue by JosephNaberhaus** [wagoid/commitlint-github-action#34]
I'm trying to setup commit-linting for [this repository](https://github.com/real-life-td/world-generator). I have an **action** set up with the following *yaml*:
```
commit-fmt:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v1.6.0
        with:
          configFile: './.commitlintrc.yml'
```
The **.commitlintrc.yml** file is just supposed to tell the linter to use the conventional config:
```
---
extends:
  - '@commitlint/config-conventional'
```

However, I get the following **error**:
```
⧗   input: feat(types.go): add structrues for capturing results returned by overpass
✖   header must not be longer than 72 characters, current length is 73 [header-max-length]
```
According to the [conventional config documentation](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) the *header-max-length* should be 100. It seems like this action is still using the [angular config](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-angular) which has a *header-max-length* of 72.
