### ISSUE TITLE
How lint every single commit in a PR?

### ISSUE THREAD

**Issue by kerry-perret** [wagoid/commitlint-github-action#36]
How can I lint every single commit in a PR?

```yaml
name: On Push

on: [push]

jobs:

  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        with:
          configFile: './.commitlintrc.yml'
          firstParent: false
          failOnWarnings: true
```

`commitlintrc.yml`:
```yaml
---
extends:
  - '@commitlint/config-conventional'
```

```bash
Run wagoid/commitlint-github-action@v15s

Run wagoid/commitlint-github-action@v1
/usr/bin/docker run --name wagoidcommitlintgithubaction160_8073c3 --label c27d31 --workdir /github/workspace --rm -e INPUT_CONFIGFILE -e INPUT_FIRSTPARENT -e INPUT_FAILONWARNINGS -e INPUT_HELPURL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_API_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/MessingUp/MessingUp":"/github/workspace" wagoid/commitlint-github-action:1.6.0
##[error]You have commit messages with errors

⧗   input: style:
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

The configuration above only checks the last commit in the PR, [see this example](https://github.com/kerry-perret/MessingUp/pull/4) =|

**Comment by wagoid** [comment]
Hi @kerry-perret! In order to lint all commits from a PR you can use `on: [pull_request]`, like in the example below:
```
name: On Pull Request

on: [pull_request]

jobs:

  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        with:
          configFile: './.commitlintrc.yml'
          firstParent: false
          failOnWarnings: true
```

If you want you can also combine and use this action both to lint a single commit and all commits from a PR, like this: `on: [push, pull_request]`

Let me know if those examples don't work :rocket:

**Comment by kerry-perret** [comment]
Hi @wagoid! Thanks for your answer, I tried what you said and turns out I'm running something really unexpected:

[`.github/workflows/build.yml`](https://github.com/kerry-perret/MessingUp/blob/meh/.github/workflows/build.yml):
```yaml
name: On Pull Request

on: [pull_request]

jobs:

  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        with:
          configFile: './.commitlintrc.yml'
          firstParent: false
          failOnWarnings: true
```

[Job Details](https://github.com/kerry-perret/MessingUp/pull/4/checks?check_run_id=789096470):
```bash
/usr/bin/docker run --name wagoidcommitlintgithubaction160_be6688 --label c27d31 --workdir /github/workspace --rm -e INPUT_CONFIGFILE -e INPUT_FIRSTPARENT -e INPUT_FAILONWARNINGS -e INPUT_HELPURL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_API_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/MessingUp/MessingUp":"/github/workspace" wagoid/commitlint-github-action:1.6.0
##[error]error trying to get list of pull request's commits
Bad credentials
HttpError: Bad credentials
    at response.text.then.message (/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
##[error]error running commitlint
Cannot read property 'Symbol(Symbol.iterator)' of undefined
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at showLintResults (/action.js:136:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Any idea about what does the job fails?

**Comment by wagoid** [comment]
Ah I think that's because the `GITHUB_TOKEN` 
env var is not set in the job. Could you try this version?

```
name: On Pull Request

on: [pull_request]

jobs:

  lint-commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        with:
          configFile: './.commitlintrc.yml'
          firstParent: false
          failOnWarnings: true
```
