### ISSUE TITLE
Is it possible to reduce the pull time for : Pull wagoid/commitlint-github-action:1.6.0

### ISSUE THREAD

**Issue by kaychess** [wagoid/commitlint-github-action#37]
Hello there, 
I am new to git actions. Please correct me if I am stating anything wrong. 

In Git actions -> jobs, I noticed that Pull wagoid/commitlint-github-action:1.6.0 step is taking
31 sec.

Is there any way to reduce this time. 

Please have a look on this issue. 

Thank you

**Comment by wagoid** [comment]
hi @kaychess!

Back when I created this action this was the fastest option available (i.e. pull the action's image from docker hub).

At that time I tried to use an `alpine-node` image to make the pull quicker but I had an issue that I couldn't get the hang of it so I just kept with the default `node` image from docker hub. I'll have a look if I can get the `alpine-node` version working again.

Also, it seems that now that Github Actions is more evolved there are options that'll probably be better than the current one. I'll also have a look at that.

Will get back to you once I have some improvements done :rocket:

**Comment by wagoid** [comment]
Hey @kaychess, I've just published version 1.7.0 which uses the alpine based image. The image's compressed size was reduced from ~352 MB to ~56 MB, which made the pull time get reduced to around ~12s as you can see [In this workflow run](https://github.com/wagoid/commitlint-github-action/runs/835383503?check_suite_focus=true) :tada: :rocket: 

I also tried to use GitHub's package registry instead of docker hub for further improvement to the pull time. Turns out their registry can't be used to host actions' source code yet because they don't allow pulling images (even public ones) without authenticating. Once they add support for that I'll add this update too :muscle:

**Comment by kaychess** [comment]
Oh Thank you very much for the update :) 
Meanwhile when I was playing with commit lint, I figured that we can use plain git actions without any docker.
All we need to do is just get the last git commit message and pipe it to the commitlint for validation. Of-couse we need to install respective commitlint node module. But installing it using git actions, we can use caching [I know we can but I dont know how yet], by which I long run should bring the time factor to around 4 to 5 sec.
 
``` YAML
name: Lint
on:
  push:
    branches:
      - master
jobs:
  git_commit_messages_lint:
    name: Git_commit_messages_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Get Last committed message and check against commit lint
        run: git log -1 --pretty=%B | npx commitlint
      - name: Check if there is any error
        if: failure()
        run: |
          echo " : Error ::: Lint : Git Commit Messages "
          exit 1
      .... Other steps ...
```
