### ISSUE TITLE
commit range revision error

### ISSUE THREAD

**Issue by ryanbas21** [wagoid/commitlint-github-action#384]
```
commit-check:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        with:
          # When set to true, we follow only the first parent commit
          # when seeing a merge commit.
          # This helps to ignore errors in commits that were already
          # present in your default branch (e.g. master) before adding
          # conventional commit checks.
          firstParent: true
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
```

I'm using this in a job like so, but i get every time a break in CI that says:
<img width="1254" alt="Screen Shot 2022-04-28 at 9 52 40 AM" src="https://user-images.githubusercontent.com/18267769/165793592-4924af26-f353-4aa2-921c-3e94d55ba8ad.png">

I saw an older issue that says fetch depth 0 solves this, but its not really solving it for me, ive tried it a few times
