### ISSUE TITLE
Dependabot doesn't use the `chore` type on my repositories; it uses `build`

### ISSUE THREAD

**Issue by philippeboyd** [wagoid/commitlint-github-action#439]
I was trying to figure out why commitlint-github-action was giving me errors for `body-max-line-length` 

<img width="828" alt="image" src="https://user-images.githubusercontent.com/3239656/172421987-b394b13a-0103-4716-ba48-e1233cb2510f.png">

Turns out we're just checking for the `chore` type in [commitlint.config.js](https://github.com/wagoid/commitlint-github-action/blob/master/commitlint.config.js)

```js
const isDepsCommit = type === 'chore' && (scope === 'deps' || scope === 'deps-dev')
```

My dependabot is giving me `build` type instead of `chore` with default configs

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
```

<img width="561" alt="image" src="https://user-images.githubusercontent.com/3239656/172421713-a4c04c6f-5d5f-4834-8854-075d5db1baaa.png">

**Comment by philippeboyd** [comment]
@jdbruijn why did you close this issue, did you take a look at my PR?

From my understanding, Dependabot creates a default commit with a `build` type unless a previous commit with perhaps an old type was created; see implementation of [build_commit_prefix_from_previous_commits](https://github.com/dependabot/dependabot-core/blob/3581084dfd0f7aff6e16a9d3c36557e664208472/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L112).

What I'm saying is that the current default [commitlint configs](https://github.com/wagoid/commitlint-github-action/blob/master/commitlint.config.js) are outdated, hence my PR #440

**Comment by jdbruijn** [comment]
I did see the PR indeed. I didn't mean to come off as rude or anything. My point is that this is essentially not an issue with this action, but rather with the used commitlint configuration. In other case dependabot might use `Upgrade: ` or `⬆️ `, depending on recent commits.

I'm pretty sure, but @wagoid could confirm if it's indeed correct, we don't even use the configuration file from this repository for anything other then the commits in this repository https://github.com/wagoid/commitlint-github-action/blob/2e578124a54b446aaf8dfa6d7c71d92e2d6a3de7/src/action.js#L122-L124 as we'll literally just extend `@commitlint/config-conventional` as fallback. The fallback being the case where there is no local configuration file, so in your repository for example. To fix this issue you should really create these rules in your local commitlint configuration file(s) and make sure it is called `commitlint.config.js` or you configure it by means of the [`configFile` option](https://github.com/wagoid/commitlint-github-action#configfile). Hope this helped clarify.

**Comment by philippeboyd** [comment]
@jdbruijn Thanks for the explanation! It was my _too quick wrong_ understanding that the file `commitlint.config.js` in this repo was also considered the default for the Github Action.

However, if I may suggest, what about having an additional config flag in the commitlint action such as `ignoreDependabot: true` if there's a way to get `who` created the commits

```yaml
name: Lint Commit Messages

on:
  - pull_request

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        with:
          ignoreDependabot: true
```

That way the github action could be compatible with dependabot without having the need for a custom `commitlint.config.js` file in the repo.
