### ISSUE TITLE
What range of commits are looked at?

### ISSUE THREAD

**Issue by michaelgwelch** [wagoid/commitlint-github-action#456]
We have a private repo so I can't share it with you. But we have two active branches going. Every Friday (or Monday) I merge from `v4` to `v5`. Four weeks in a row this merge is failed due to the commitlint-github-action.

When I look at the details I see old commit messages that are not included in the current PR that are failing. 

I would expect it to just be examining the handful of commits that are from `v4` that are new to `v5` and not older commit messages that were committed prior to our use of commitlint.

What data could I provide to help debug this issue?

this is our job definition (run on pull request):

```
jobs:
  lint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
```
