### ISSUE TITLE
Unexpected input(s) 'helpUrl'

### ISSUE THREAD

**Issue by f-squirrel** [wagoid/commitlint-github-action#49]
Warning about `helpUrl` in the actions annotation:
https://github.com/f-squirrel/concord-bft/actions/runs/238194122

Please advise.

**Comment by wagoid** [comment]
hi @f-squirrel! Looks like you're providing the `helpUrl` param to the wrong action (`actions/checkout`). The correct workflow file for your case would be the following:

```yaml
name: Lint Commit Messages
on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - uses: wagoid/commitlint-github-action@v2
        with:
          helpUrl: https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#rules
```
