### ISSUE TITLE
Cannot find module 'conventional-changelog-conventionalcommits'

### ISSUE THREAD

**Issue by BenjaminRochez** [wagoid/commitlint-github-action#552]
When using the latest version (5.1.2) in the CI we get this error

```
error running commitlint
Cannot find module 'conventional-changelog-conventionalcommits'
```

Thanks for your help

**Comment by BenjaminRochez** [comment]
```
name: review-branch
on:
  push:
    branches-ignore:
      - master
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
``` 
We tried to pin it to v5.1.2 but it didn't work either. We pinned it to v4.1.15 which does the job.
