### ISSUE TITLE
Fails to run with error: Unable to compile TypeScript error

### ISSUE THREAD

**Issue by tgallacher** [wagoid/commitlint-github-action#560]
# Summary

This action failed to run on a Typescript project, with a `tsconfig.json`. Received the following error:

```sh
error running commitlint
⨯ Unable to compile TypeScript:
error TS6053: File '<redacted>' not found.

TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '<redacted>' not found.

    at createTSError (/node_modules/ts-node/src/index.ts:859:[12])
    at reportTSError (/node_modules/ts-node/src/index.ts:863:19)
    ...
```

The `<redacted>` "file" is an internal TS config package (private registry).

This is the Github workflow:

```yml
name: Standards

on:
  pull_request:

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # required to get all history, not just commit that triggers current run
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
```

This issue appears to be related to https://github.com/conventional-changelog/commitlint/issues/3256. 

Note: I managed to find a workaround by downgrading to `v4` of this action: `wagoid/commitlint-github-action@v4`

**Comment by wagoid** [comment]
Hi @tgallacher, thanks for submitting this issue! Looks like we'll need to wait for commitlint to fix this issue, as ths workaround from [this comment](https://github.com/conventional-changelog/commitlint/issues/3256#issuecomment-1167343823) is not possible in this action.

The good thing is that it doesn't happen on all Typescript projects, I run this action in other TS projects and it doesn't fail 😌 

Another workaround I can suggest to you, so that you can keep running this action in v5, is to delete `tsconfig.json` right before linting:
```yaml
name: Standards

on:
  pull_request:

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # required to get all history, not just commit that triggers current run
        with:
          fetch-depth: 0

      - run: rm tsconfig.json

      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
```

I can't run this `rm tsconfig.json` as part of this action's workflow since this may impact people's workflows, so I can only suggest as a workaround on your case. I'll close this issue, but let me know if you need any more help 💪
