### ISSUE TITLE
Error message : Cannot find module 'tsconfig-paths/register'

### ISSUE THREAD

**Issue by laurentvasseurtekos** [wagoid/commitlint-github-action#617]
Hello, thank you for this Github action, it is really useful. 

I currently have an error when I launch this github action in v5.

This is how I declare it in my github action workflow : 

```yaml
  commitlint:
    name: 'Lint Commit Messages'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
```

You can find the error message below : 

```
error running commitlint
Cannot find module 'tsconfig-paths/register'
Require stack:
- /node_modules/ts-node/dist/util.js
- /node_modules/ts-node/dist/index.js
- /node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js
- /node_modules/@commitlint/load/lib/utils/load-config.js
- /node_modules/@commitlint/load/lib/load.js
- /run.js
Error: Cannot find module 'tsconfig-paths/register'
Require stack:
- /node_modules/ts-node/dist/util.js
- /node_modules/ts-node/dist/index.js
- /node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js
- /node_modules/@commitlint/load/lib/utils/load-config.js
- /node_modules/@commitlint/load/lib/load.js
- /run.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.resolve (node:internal/modules/cjs/helpers:99:19)
    at projectLocalResolveHelper (/node_modules/ts-node/dist/util.js:117:24)
    at /node_modules/ts-node/dist/configuration.js:159:61
    at Array.map (<anonymous>)
    at readConfig (/node_modules/ts-node/dist/configuration.js:159:47)
    at findAndReadConfig (/node_modules/ts-node/dist/configuration.js:50:84)
    at create (/node_modules/ts-node/dist/index.js:146:69)
    at register (/node_modules/ts-node/dist/index.js:127:19)
    at TypeScriptLoader (/node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js:52:54)
```

When I use the github action in v4, I don't have any issue. 
Do you encounter the same problem ? 

Thank you for your help
