### ISSUE TITLE
Raw commit error

### ISSUE THREAD

**Issue by OopsYao** [wagoid/commitlint-github-action#66]
I used this action in a `pull_request_target` workflow, and I checked to the head branch (from a private fork PR) before linting. The commits in this pr have a bad message format. But It just ignored the bad commit message at PR open (said `Lint free! 🎉`). And after new commit was pushed to the PR, it threw the following error.

## Action log

```
Run wagoid/commitlint-github-action@v2.0.3
  with:
    configFile: .commitlintrc.yml
    firstParent: true
    failOnWarnings: false
    helpURL: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
    token: ***
/usr/bin/docker run --name wagoidcommitlintgithubaction203_f31bcd --label 179394 --workdir /github/workspace --rm -e INPUT_CONFIGFILE -e INPUT_FIRSTPARENT -e INPUT_FAILONWARNINGS -e INPUT_HELPURL -e INPUT_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/playground/playground":"/github/workspace" wagoid/commitlint-github-action:2.0.3
Error: error running commitlint
Expected a raw commit
TypeError: Expected a raw commit
    at parser (/node_modules/conventional-commits-parser/lib/parser.js:79:11)
    at sync (/node_modules/conventional-commits-parser/index.js:97:10)
    at Object.parse [as default] (/node_modules/@commitlint/parse/lib/index.js:8:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async lint (/node_modules/@commitlint/lint/lib/lint.js:29:11)
    at async /src/action.js:130:19
    at async Promise.all (index 0)
    at async showLintResults (/src/action.js:128:25)
```

And here is my workflow file:
```yaml
name: CI
on:
  push:
    branches: "**"
  pull_request_target:
    branches: master

jobs:
  commit-lint:
    name: Lint Commit
    runs-on: ubuntu-18.04
    if: github.event_name == 'pull_request_target'
    steps:
      - name: Checkout head # Run lint commit against the head branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # fetch all commits for linting
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_PAT }} # use this token to checkout a private fork
          persist-credentials: false
      - name: Commit linter
        uses: wagoid/commitlint-github-action@v2.0.3
        id: commitlint
        with:
          configFile: .commitlintrc.yml
```
and the `.commitlintrc.yml`:
```yaml
extends:
  - "@commitlint/config-conventional"
```
