### ISSUE TITLE
helpURL input should overrule configuration

### ISSUE THREAD

**Issue by korthout** [wagoid/commitlint-github-action#705]
I used the following in my workflow:

```yaml
- uses: wagoid/commitlint-github-action@v5
  with:
    commitDepth: ${{ github.event.pull_request.commits }}
    helpURL: http://acme.com/example-url
```

To my surprise, the workflow logs contained:
>Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

This is because my very basic config pulled in the `helpUrl` from `@commitlint/config-conventional`. 
```js
module.exports = { extends: ['@commitlint/config-conventional'] };
```

To me, this was unexpected because I explicitly told the action to use `http://acme.com/example-url`  as the `helpURL`. 

I would propose to flip the sides of the `||` or operator [here](https://github.com/wagoid/commitlint-github-action/blob/master/src/action.js#L106) so the defined inputs are favored over the configuration:
```js
helpUrl: getInput('helpURL') || config.helpUrl,
```

**Comment by SvenStaehs** [comment]
This happens even without an extended config; I don't have a config file at all and the helpURL is still not honored. Full config of my step:

``` yaml
      - uses: actions/wagoid_commitlint-github-action@456526eec71276a59e74aafdfe06a9632ac2eee1 # v5.4.1
        with:
          helpURL: "${{ github.server_url }}/${{ github.repository }}/blob/main/CONTRIBUTING.md"
```

Here's the output I get (with details redacted)
> Run actions/wagoid_commitlint-github-action@456526eec71276a59e74aafdfe06a9632ac2eee1
>   with:
>     helpURL: https://myGHES/myOrga/myRepo/blob/main/CONTRIBUTING.md
>     configFile: ./commitlint.config.js
>     firstParent: true
>     failOnWarnings: false
>     failOnErrors: true
>     token: ***
> /usr/bin/docker run --name wagoidcommitlintgithubaction541_242aeb [...] wagoid/commitlint-github-action:5.4.1
> Error: You have commit messages with errors
> 
> [...]
> 
> ✖   found 2 problems, 0 warnings
> ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

So it correctly sets the input, but it has no effect.
