### ISSUE TITLE
error running commitlint:  Invalid revision range ..

### ISSUE THREAD

**Issue by mydearxym** [wagoid/commitlint-github-action#73]
hi there ~

i am follow the README setting up this action, but got error:

https://github.com/coderplanets/coderplanets_server/runs/1828372565?check_suite_focus=true

![image](https://user-images.githubusercontent.com/6184465/106850348-50939c00-66ef-11eb-9cb2-4170f0475e0e.png)

what is the term 'fatal: Invalid revision range' mean ?

**Comment by jdbruijn** [comment]
I'm pretty sure it has to do with the checkout. Could you please share your workflow for so we can have a look at it?

What I'm suspecting now is that your checkout step is with fetch depth zero, thus containing only one commit. FYI, this is the workflow I use, see the checkout step!

```yml
name: Lint commit messages
on:
  push:
    branches:
      - master
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v2.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
