### ISSUE TITLE
Error running commitlint require() of ES Module

### ISSUE THREAD

**Issue by VictorPulzz** [wagoid/commitlint-github-action#758]
Problem description
When tried to run the action received the follow error:
require() of ES Module /github/workspace/node_modules/@commitlint/config-conventional/lib/index.js from /node_modules/@commitlint/resolve-extends/lib/index.js not supported...

Screenshot:
![image](https://github.com/wagoid/commitlint-github-action/assets/23406402/1ebc116b-21f1-4e23-bb83-a0231b255ce3)

Adicional info
My workflow file:
```yml
name: Release

#on:
#  push:
#    branches:
#      - master

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm test

      - name: Reset changes from integration unit tests
        run: git reset --hard HEAD

      - name: Build
        run: npm run build

      - name: Type check
        run: npm run check-types

      - name: Code linting check
        run: npm run lint

      - name: Code formatting
        run: npm run prettier

      - name: Commit formatting check
        uses: wagoid/commitlint-github-action@v5
```
