### ISSUE TITLE
Question: how to set configFile?

### ISSUE THREAD

**Issue by belozer** [wagoid/commitlint-github-action#8]
I didn't fully understand how to do it.

```yml
name: Commitlint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1

      - uses: wagoid/commitlint-github-action@v1.2.0
        with:
          configFile: './.commitlintrc.json'
```

![image](https://user-images.githubusercontent.com/1655916/67055893-860b2380-f152-11e9-9720-8876c2640444.png)

Where is my mistake?
